name: hrapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  antd_mobile: ^0.1.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get: ^5.0.0-release-candidate-9.2.1
  flutter_speed_dial: ^7.0.0
  http: ^1.2.2
  get_storage: ^2.1.1
  dropdown_textfield: ^1.2.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

  shimmer: ^3.0.0
  show_hide_password: ^0.0.2
  flutter_launcher_icons: ^0.14.1
  ribbon_widget: ^1.0.5
  percent_indicator: ^4.2.3
  google_fonts: ^6.2.1
  number_to_words: ^1.0.0
  number_to_words_english: ^2.0.2

  flutter_localization: ^0.2.2
  flutter_local_notifications: ^18.0.1
  lottie: ^3.1.3
  upgrader: ^11.3.1
  curved_labeled_navigation_bar: ^2.0.6
  confetti: ^0.8.0
  local_auth: ^2.3.0
  flutter_filter_dialog: ^1.2.0
  flutter_slidable: ^3.1.2
  grouped_list: ^6.0.0
  intl: ^0.20.2
  month_picker_dialog: ^6.2.1

  google_maps_flutter: ^2.12.2
  timelines_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/6.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/6.png"

flutter:
  uses-material-design: true
  assets:
    - assets/primaryBg.png
    - assets/images/calendar.png
    - assets/images/salary.png
    - assets/images/leave.png
    - assets/images/Attendence-removebg-preview.png
    - assets/images/travel.png
    - assets/images/leave (7).png
    - assets/images.png
    - assets/calendar.png
    - assets/exit.png
    - assets/immigration.png
    - assets/salary (1).png
    - assets/paycheck.png
    - assets/leave (1).png
    - assets/leave.png
    - assets/save-instagram.png
    - assets/leave (2).png
    - assets/leave (4).png
    - assets/leave (5).png
    - assets/Mada.png
    - assets/Signature.jpg
    - assets/istockphoto-.png
    - assets/removebg-preview.png
    - assets/Main_Logo-removebg-preview.png
    - assets/logo-removebg (1).png
    - assets/redlogo.png
    - assets/Untitled_design-removebg-preview.png
    - assets/RS-HRMS.png
    - assets/lottie/Animation - 1732192021112.json
    - assets/lottie/Animation - 1747201510561.json
    - assets/images/timer.webp
    - assets/Logo-removebg-preview (2).png
    - assets/Main_Logo-removebg-preview.png
    - assets/lottie/Loading.json
